apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  RATE_LIMIT_MESSAGES: "100"
  RATE_LIMIT_WINDOW: "60"
  AWS_REGION: "us-east-1"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
